export const GET_USERS_REQUEST = "GET_USERS_REQUEST"
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS"
export const GET_USERS_FAIL = "GET_USERS_FAIL"

export const GET_ADD_NEW_USERS = "GET_ADD_NEW_USERS"
export const GET_EDIT_USERS = "GET_EDIT_USERS"
export const GET_UPDATE_USER = "GET_UPDATE_USER"
